config/routes.rb
Rails.application.routes.draw do
  root "air_quality#index"
  get "air_quality", to: "air_quality#index"
end

app/controllers/air_quality_controller.rb
class AirQualityController < ApplicationController
  require "httparty"

  def index
    respond_to do |format|
      format.html
      format.turbo_stream do
        url = "#{Rails.application.credentials.dig(:air_quality_api, :base_url)}/api/v1/getCityRankByCitySlug"
        headers = {
          "Authorization" => "bearer #{Rails.application.credentials.dig(:air_quality_api, :bearer_token)}",
          "cityslug" => "indonesia/jawa-barat/bandung",
          "sensorname" => "aqi"
        }
        response = HTTParty.get(url, headers: headers)
        if response.success?
          @data = response.parsed_response["data"]
          @aqius = @data["location"]["aqius"]
          @aqi_levels = [
            { range: 0..50, color: "bg-green-400", status: "Good", index: "0 to 50", description: "Air quality is satisfactory, and air pollution poses little or no risk." },
            { range: 51..100, color: "bg-yellow-400", status: "Moderate", index: "51 to 100", description: "Air quality is acceptable. However, there may be a risk for some people, particularly those who are unusually sensitive to air pollution." },
            { range: 101..150, color: "bg-orange-400", status: "Unhealthy for Sensitive Groups", index: "101 to 150", description: "Members of sensitive groups may experience health effects. The general public is less likely to be affected." },
            { range: 151..200, color: "bg-red-400", status: "Unhealthy", index: "151 to 200", description: "Some members of the general public may experience health effects; members of sensitive groups may experience more serious health effects." },
            { range: 201..300, color: "bg-purple-400", status: "Very Unhealthy", index: "201 to 300", description: "Health alert: The risk of health effects is increased for everyone." },
            { range: 301..500, color: "bg-rose-700", status: "Hazardous", index: "301 and higher", description: "Health warning of emergency conditions: everyone is more likely to be affected." }
          ]
          selected_level = @aqi_levels.find { |level| level[:range].include?(@aqius) } || @aqi_levels.last
          @bg_color = selected_level[:color]
          @level_status = selected_level[:status]
          @value_of_index = selected_level[:index]
          @description = selected_level[:description]
        else
          @error = "Failed to fetch air quality data."
        end
        # Render the Turbo Stream response
        render turbo_stream: turbo_stream.replace("air_quality_data", partial: "air_quality/data", locals: {
          data: @data,
          bgColor: @bg_color,
          levelStatus: @level_status,
          valueOfIndex: @value_of_index,
          description: @description,
          aqiLevels: @aqi_levels,
          error: @error
        })
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/helpers/air_quality_helper.rb
module AirQualityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/air_quality/_data.html.erb
<% if error.present? %>
  <p class="mt-4 text-red-500 font-bold"><%= error %></p>
<% else %>
  <div class="min-h-screen flex flex-col items-center justify-center <%= bgColor %> pt-6 pb-24 pl-6 pr-6">
    <!-- Main AQI Card -->
    <div class=" bg-white shadow-md rounded-xl p-6 text-center">
      <p class="text-sm">📍 <span class="font-semibold"><%= data["location"]["cityName"] %>, <%= data["location"]["stateName"] %>, <%= data["location"]["countryName"] %></span></p>
      <p class="font-semibold text-8xl mt-4 mb-4"><%= data["location"]["aqius"] %></p>
      <p class="text-sm">Air Quality Index (US Standard)</p>
      <p class="text-xs text-right mt-4"><%= data["location"]["timeStamp"] %></p>
    </div>
    <!-- AQI Level of Concern -->
    <div class="mt-2 bg-white shadow-md rounded-lg p-6 w-full max-w-screen-md">
      <p class="text-sm">Level of Concern: <span class="font-semibold text-lg underline"><%= levelStatus %></span></p>
      <p class="text-sm">Description of Air Quality: <span class="font-semibold text-lg"><%= description %></span></p>
      <p class="mt-4 text-xs text-right">
        Source: 
        <a href="<%= data["location"]["sourceUrl"] %>" class="font-semibold text-xs text-blue-500 underline" target="_blank">
          <%= data["location"]["source"] %>
        </a>
      </p>
    </div>
    <!-- AQI Levels List -->
    <div class="mt-2 bg-white shadow-md rounded-lg p-6 w-full max-w-screen-md">
      <h3 class="text-sm font-bold mb-2">AQI Basics for Ozone and Particle Pollution</h3>
      <ul class="space-y-2">
        <% aqiLevels.each do |level| %>
          <li class="p-2 rounded-lg <%= level[:color] %> text-white text-sm">
            <span class="font-semibold"><%= level[:status] %></span>
            (<%= level[:index] %>) - <%= level[:description] %>
          </li>
        <% end %>
      </ul>
      <p class="mt-4 text-xs text-right">
        Source: 
        <a href="https://www.airnow.gov/aqi/aqi-basics/" class="font-semibold text-xs text-blue-500 underline" target="_blank">airnow.gov</a>
      </p>
    </div>
    <!-- Footer with Social Media Icons -->
    <footer class="fixed rounded-t-2xl bottom-0 left-0 right-0 bg-gray-800 text-white p-4 flex justify-center space-x-4">
      <a href="https://www.linkedin.com/in/farizramadhan" target="_blank" class="text-blue-400 hover:text-blue-500">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M4.98 3.5C3.89 3.5 3 4.4 3 5.5s.89 2 1.98 2c1.1 0 1.99-.9 1.99-2s-.89-2-1.99-2zM3 8h3v12H3V8zm5 0h3v1.5c.64-1.18 2.14-2.04 3.84-2.04 4.1 0 4.86 2.7 4.86 6.21V20h-3v-5.62c0-1.34-.03-3.08-1.89-3.08-1.89 0-2.18 1.47-2.18 2.99V20H8V8z"/>
        </svg>
      </a>
      <a href="https://github.com/farizdotid" target="_blank" class="text-gray-400 hover:text-gray-500">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 2C6.48 2 2 6.48 2 12c0 4.42 2.87 8.16 6.84 9.49.5.09.66-.21.66-.47v-1.69c-2.78.61-3.37-1.21-3.37-1.21-.46-1.15-1.13-1.45-1.13-1.45-.92-.63.07-.62.07-.62 1.02.07 1.55 1.05 1.55 1.05.91 1.55 2.39 1.1 2.97.84.09-.66.36-1.1.65-1.35-2.22-.25-4.56-1.11-4.56-4.92 0-1.09.39-1.98 1.03-2.68-.1-.26-.45-1.27.1-2.64 0 0 .84-.27 2.75 1.03a9.44 9.44 0 015 0c1.91-1.3 2.75-1.03 2.75-1.03.55 1.37.2 2.38.1 2.64.64.7 1.03 1.59 1.03 2.68 0 3.82-2.34 4.66-4.57 4.91.37.32.7.94.7 1.9v2.82c0 .27.16.58.67.47A10.01 10.01 0 0022 12c0-5.52-4.48-10-10-10z"/>
        </svg>
      </a>
      <a href="https://www.farizlogs.com/" target="_blank" class="text-gray-400 hover:text-gray-500">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
        </svg>
      </a>
    </footer>
  </div>
</div>
<% end %>

app/views/air_quality/index.html.erb
<%= turbo_frame_tag "air_quality_data", src: air_quality_path(format: :turbo_stream) do %>
  <div class="min-h-screen flex flex-col items-center justify-center space-x-2">
    <svg class="animate-spin h-8 w-8 text-blue-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
      <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
      <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"></path>
    </svg>
    <p class="text-gray-700">Loading air quality data...</p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Air Quality" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

     <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>